---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  annotations:
    load-balancer.hetzner.cloud/ipv6-disabled: "true"
    load-balancer.hetzner.cloud/location: ash
    external-dns.alpha.kubernetes.io/hostname: istio-ingress.k8s.unreliable.cloud