---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
spec:
  template:
    spec:
      containers:
        - name: discovery
          resources:
            limits:
              cpu: 1
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 2048Mi