apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches/ingressgateway-hetzner.yaml
  target:
    kind: Service
- path: patches/istiod-resources.yaml
  target:
    kind: Deployment
    name: istiod