---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  selector:
    matchLabels:
      operator.istio.io/component: "IngressGateways"
  accessLogging:
    - providers:
      - name: envoy
