---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: access-logging-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      operator.istio.io/component: "IngressGateways"
  accessLogging:
    - providers:
      - name: envoy
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: prometheus-metrics
  namespace: blog
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        request_method:
          value: "request.method"
        request_host:
          value: "request.host"
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: prometheus-metrics
  namespace: freshrss
spec:
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - tagOverrides:
        request_method:
          value: "request.method"
        request_host:
          value: "request.host"