---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
spec:
  template:
    metadata:
      annotations:
        ad.datadoghq.com/istio-proxy.check_names: '["openmetrics"]'
        ad.datadoghq.com/istio-proxy.init_configs: '[{}]'
        ad.datadoghq.com/istio-proxy.instances: |
          [
            {
              "openmetrics_endpoint": "http://%%host%%:15020/metrics"
            }
          ]
        ad.datadoghq.com/istio-proxy.logs: '[{"source": "json", "service": "istio-ingressgateway"}]'
    spec:
      containers:
        - name: istio-proxy
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 250Mi
